---
# tasks file for db-tier

- name: install postgres server
  yum:
    name: postgresql-server
    state: latest

- name: enable apache on boot
  service:
    name: postgresql
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: check file postgresql conf
  stat:
    path: "{{ postgres_conf_file }}"
  register: pgsql_conf

- name: initilize postgres
  command: postgresql-setup initdb
  when: not pgsql_conf.stat.exists

#- name: copy file postgresql conf
#  template:
#    src: postgresql.conf.j2
#    dest: "{{ postgres_conf_file }}"
#    force: no
#  register: pgsql_conf

- name: start postgres
  service:
    name: postgresql.service
    state: started
    enabled: yes
